export const initialValues = {
  firstName: "",
  lastName: "",
  password: "",
  userSupervicer: "",
  birthday: "",
  arriveDate: "",
  availableVacationsDays: "",
  availableStudyDays: "",
  dni: "",
  cuil: "",
  email: "",
  cellphone: "",
  postalCode: "",
  tower: "",
  floor: "",
  flat: "",
  city: "",
  province: "",
  country: "",

  administrator: true,
};
